@startuml "Diagrama de Casos de Uso"

actor "Usuário" as Usuario

left to right direction

rectangle "Sistema Pomodoro" {

    usecase "Cadastrar Configuracoes" as CadastrarConfiguracoes

    usecase "Iniciar Pomodoro" as IniciarPomodoro
    usecase "Pausar Pomodoro" as PausarPomodoro
    usecase "Reiniciar Pomodoro" as ReiniciarPomodoro
    usecase "Encerrar Pomodoro" as EncerrarPomodoro	
    usecase "Exibir Cronômetro" as ExibirCronometro

    usecase "Notificar Pausa" as NotificarPausa
    usecase "Alarme para Início" as AlarmeInicio
    
    usecase "Gerar Relatório Gráfico" as GerarRelatorio

    Usuario --> IniciarPomodoro
    Usuario -right-> CadastrarConfiguracoes
    Usuario -right-> GerarRelatorio
    
    IniciarPomodoro --> ExibirCronometro : "<<include>>"
    IniciarPomodoro --> AlarmeInicio : "<<include>>"

    PausarPomodoro .up.|> IniciarPomodoro : "<<extend>>"
    ReiniciarPomodoro .up.|> IniciarPomodoro : "<<extend>>"
    EncerrarPomodoro .up.|> IniciarPomodoro : "<<extend>>"
    AlarmeInicio --> NotificarPausa : "<<include>>"
    
}

@enduml
