@startuml "Diagrama de Classes"

class Usuario {
    - List<Pomodoro> historicoPomodoro
    + obterRelatorioMensal(): Relatorio
}

class Pomodoro {
    - int tempoEstudo
    - int tempoPausa
    - Date data
    - boolean concluido

    + iniciarPomodoro(tempoEstudo: int, tempoPausa: int)
    + iniciar()
    + pausar()
    + reiniciar()
}

class Temporizador {
    - int tempoAtual
    - boolean rodando
    + iniciar()
    + pausar()
    + reiniciar()
    + getTempoAtual(): int
}

class Notificacao {
    + exibirMensagem(mensagem: String)
    + tocarSom()
}

class Relatorio {
    - List<Pomodoro> dadosPomodoro
    + gerarGraficoMensal()
}

Usuario -down-> Pomodoro : "Usa"
Usuario --> Relatorio : "Gera"
Pomodoro -> Temporizador : "Controla"
Pomodoro -down-> Notificacao : "Exibe Alerta"
Relatorio -> Pomodoro : "Usa dados"

@enduml
